name: CI Workflow
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:

  linters:
    name: Linter Check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install linters
      run: |
        cd /tmp && go get -u golang.org/x/lint/golint
        sudo npm install -g jshint
      env:
        GO111MODULE: off
    - name: Run golint
      run: |
        export PATH=/home/runner/go/bin:$PATH
        make lint
    - name: Run jshint
      run: jshint ui/static/js/*.js

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: go-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run unit tests
      run: make test

  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sassospicco/miniflux/miniflux
          tag_with_ref: true
