name: CI Workflow
on:
  pull_request:
    branches:
    - master
  push:
  workflow_dispatch:

jobs:

  linters:
    name: Linter Check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install linters
      run: |
        cd /tmp && go get -u golang.org/x/lint/golint
        sudo npm install -g jshint
      env:
        GO111MODULE: off
    - name: Run golint
      run: |
        export PATH=/home/runner/go/bin:$PATH
        make lint
    - name: Run jshint
      run: jshint ui/static/js/*.js

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run unit tests
      run: make test

  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/sassospicco/miniflux:latest
